### ISSUE TITLE
tracking: Work on API.

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#202]
Some thoughts while trying to rewrite [meli](https://meli.delivery/)'s IMAP backend with imap-codec.

* [x] #205
  * [x] #241
* [x] #204
* [x] Implement "plug&play" literal encoding and handling for quick replacement of existing code.
* [x] Expose `CapabilityEnableOther{,Error}` in public API. Or not? 🤔
* [x] Use `const fn` where possible. -> postpone
* [x] #220
  * Literals -> Can't fail because all values were already verified.
  * Constructors -> Can fail because verification is done.
  * Unverified -> Won't fail but must be used with care.
    * Make them only accept `'static`? (Caveats ahead.)
    * How much can `const fn` help here?
    * Macros?
* [x] #219
