### ISSUE TITLE
Resolve test-related `TODO`s.

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#30]
* [ ] Resolve `TODO`s in fuzz-targets, i.e., do not skip variants.
  * [ ] `response_to_bytes_and_back` remaining
    * [ ] `BodyStructure`
    * [ ] `Continue`
* [x] Resolve `TODO`s in `Arbitrary` implementations, i.e., do not generate static values.
