### ISSUE TITLE
feat: Implement `BINARY`

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#444]
See [IMAP4 Binary Content Extension](https://datatracker.ietf.org/doc/html/rfc3516), [Collected Extensions to IMAP4 ABNF](https://datatracker.ietf.org/doc/html/rfc4466), and [IMAP4 Non-synchronizing Literals](https://datatracker.ietf.org/doc/html/rfc7888).

Note: BINARY and LITERAL+ can both be used. `~{123+}\r\n` is valid, too.

# TODO

* [x] Define `literal8` (#445) (needed for #432).

```abnf
literal8 = "~{" number "}" CRLF *OCTET
```

* [x] Extend `append` (to allow `literal8` as well). (#451)

```abnf
append /= "APPEND" SP mailbox [SP flag-list] [SP date-time] SP literal8
```

* [x] Extend `fetch-att`.

```abnf
fetch-att =/ "BINARY" [".PEEK"] section-binary [partial] /
             "BINARY.SIZE" section-binary

section-binary = "[" [section-part] "]"

partial = "<" number "." nz-number ">"
```

* [x] Extend `msg-att-static`.

```abnf
msg-att-static =/ "BINARY" section-binary SP (nstring / literal8) /
                  "BINARY.SIZE" section-binary SP number
```

* [x] Extend `resp-text-code`.

```abnf
resp-text-code =/ "UNKNOWN-CTE"
```

* [x] Add `Capability::Binary` (#451)
* [x] Remove `#[allow(unused)]` for `literal8`.

# Notes

* BINARY does not "generically" change how literals work. So, `~{123}` must only be used during the cases defined above. Not, e.g., in all `astring`s.
